### ISSUE TITLE
Non-commercial open source project support

### ISSUE THREAD

**Issue by HiFiPhile** [IARSystems/bx-github-ci#4]
Hi,

I'm a maintainer of [TinyUSB](https://github.com/hathach/tinyusb), the most widely used open-source cross-platform USB Host/Device stack for embedded system. It's also used by Espressif ESP-IDF and Raspberry Pi Pico SDK.

We'd like to integrate IAR into Github CI, I want to know what option we have :
- Is IAR Build Tool offer license to non-commercial open source project ?
- Can we use IAR EWARM with 32k evaluation license ? (So a Windows runner is needed)

Thanks,

**Comment by HiFiPhile** [comment]
Thanks for your support ! Now TinyUSB has integrated IAR CI :https://github.com/hathach/tinyusb/tree/support-iar

**Comment by hathach** [comment]
thank you for the opensource license, initial IAR support for stm32 (f0, f1 ,f3, f4, f7, g4, h7, l0) are already ported to build with IAR BX tools. https://github.com/hathach/tinyusb/pull/1876

There may be more ports in the future, but this is as good as it could get for initial PR.

**Comment by felipe-iar** [comment]
Excellent news, @hathach!
